grpc:
  server:
    port: 59091
    reflection-service-enabled: true

kafka:
  bootstrap-servers: localhost:9092
  topics:
    hubs: telemetry.hubs.v1
    sensors: telemetry.sensors.v1
  serializers:
    key: "org.apache.kafka.common.serialization.StringSerializer"
    value: "ru.yandex.practicum.serializer.AvroSerializer"

#server:
#  port: 8081